### ISSUE TITLE
Potential incompatibility with jest-lua

### ISSUE THREAD

**Issue by vocksel** [pesde-pkg/pesde#14]
I'm working on a PR to migrate Flipbook over to Pesde (https://github.com/flipbook-labs/flipbook/pull/293) and when running unit tests I'm finding that Jest is erroring for all of them with the following:

```
  ● Test suite failed to run

    unable to find environment 'jest-environment-roblox'

      ReplicatedStorage.Packages..pesde.wally#jsdotlua+jest-runner.3.6.1-rc.2.jest-runner.runTest:160
      ReplicatedStorage.Packages..pesde.wally#jsdotlua+promise.3.5.2.promise:172 function runExecutor
      ReplicatedStorage.Packages..pesde.wally#jsdotlua+promise.3.5.2.promise:181
      ReplicatedStorage.Packages..pesde.wally#jsdotlua+promise.3.5.2.promise:1245
      ReplicatedStorage.Packages..pesde.wally#jsdotlua+promise.3.5.2.promise:172 function runExecutor
      ReplicatedStorage.Packages..pesde.wally#jsdotlua+promise.3.5.2.promise:299
```

It seems like Jest's traversal up its ancestry may be getting tripped up by Pesde's index structure. Here's some relevant line's from the `runTest` function that's failing: 

https://github.com/jsdotlua/jest-lua/blob/main/src/jest-runner/src/runTest.lua#L151-L162

**Comment by daimond113** [comment]
Good catch! The issue stems from the fact Wally nests their dependencies a level less than pesde, since they name their `_Index` entries as `{scope}_{name}@{version}` while pesde uses a subfolder such as `{scope}+{name}/{version}`. This will be fixed in the next release.
